# service/src/doc_agent/prompts/__init__.py
"""
Prompts 模块

包含所有用于文档生成的提示词模板
"""

from .outline_generation import V1_DEFAULT as OUTLINE_GENERATION_PROMPT
from .planner import V1_DEFAULT as PLANNER_PROMPT
from .writer import V1_DEFAULT as WRITER_PROMPT, V1_SIMPLE as WRITER_PROMPT_SIMPLE
from .supervisor import V1_METADATA_BASED as SUPERVISOR_PROMPT
from .content_processor import (V1_DEFAULT_RESEARCH_DATA_SUMMARY,
                                V1_DEFAULT_KEY_POINTS_EXTRACTION,
                                V1_DEFAULT_CONTENT_COMPRESSION)

# 为了向后兼容，创建别名
RESEARCH_DATA_SUMMARY_PROMPT = V1_DEFAULT_RESEARCH_DATA_SUMMARY
KEY_POINTS_EXTRACTION_PROMPT = V1_DEFAULT_KEY_POINTS_EXTRACTION
CONTENT_COMPRESSION_PROMPT = V1_DEFAULT_CONTENT_COMPRESSION

__all__ = [
    'OUTLINE_GENERATION_PROMPT', 'PLANNER_PROMPT', 'WRITER_PROMPT',
    'WRITER_PROMPT_SIMPLE', 'SUPERVISOR_PROMPT',
    'RESEARCH_DATA_SUMMARY_PROMPT', 'KEY_POINTS_EXTRACTION_PROMPT',
    'CONTENT_COMPRESSION_PROMPT'
]
